# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='directory',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='longdescription',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screen',
            name='sequenceids',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
    ]
