# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0002_auto_20160301_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='pssdatapoint',
            name='radius',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
