# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 15:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uniqueref', '0003_pssdatapoint_radius'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomTracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('genelist', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom track (list of genes)',
                'verbose_name_plural': 'Custom tracks (list of genes)',
            },
        ),
    ]
