# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 12:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('uniqueref', '0004_customtracks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='screen',
            name='carried_out_by_id',
        ),
        migrations.AddField(
            model_name='screen',
            name='scientist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='screenpermissions',
            name='relscreen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniqueref.Screen'),
        ),
        migrations.AddField(
            model_name='screen',
            name='groups',
            field=models.ManyToManyField(through='uniqueref.ScreenPermissions', to='auth.Group', verbose_name=b'Group permissions'),
        ),
    ]
