# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0005_auto_20160728_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(max_length=10)),
                ('changes', models.TextField()),
            ],
            options={
                'verbose_name': 'Changelog',
                'verbose_name_plural': 'changelogs',
            },
        ),
    ]
