# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 13:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0006_updatehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 7, 13, 37, 37, 99092, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
