# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-07 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0007_auto_20161207_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatehistory',
            name='date',
            field=models.DateField(),
        ),
    ]
