# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0008_auto_20161207_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeqSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_dist', models.TextField()),
                ('high_readsmappedtotophits', models.TextField()),
                ('high_topreads_counts', models.TextField()),
                ('high_totalmappedreads', models.IntegerField()),
                ('high_totalreads', models.IntegerField()),
                ('high_totaltopreads', models.IntegerField()),
                ('high_totaluniquereads', models.IntegerField()),
                ('low_dist', models.TextField()),
                ('low_readsmappedtotophits', models.TextField()),
                ('low_topreads_counts', models.TextField()),
                ('low_totalmappedreads', models.IntegerField()),
                ('low_totalreads', models.IntegerField()),
                ('low_totaltopreads', models.IntegerField()),
                ('low_totaluniquereads', models.IntegerField()),
                ('relscreen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uniqueref.Screen')),
            ],
            options={
                'verbose_name': 'Summary of IPS screen sequencing results',
                'verbose_name_plural': 'summaries of IPS screen sequencing results',
            },
        ),
    ]
