# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-15 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0009_seqsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomVariables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_track_list_for_summary', models.IntegerField()),
            ],
            options={
                'verbose_name': 'custom variable',
                'verbose_name_plural': 'custom variables',
            },
        ),
        migrations.AlterModelOptions(
            name='seqsummary',
            options={'verbose_name': 'Summary of screen sequencing results', 'verbose_name_plural': 'summaries of screen sequencing results'},
        ),
    ]
