# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0011_slsdatapoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slsdatapoint',
            name='senseratio',
            field=models.FloatField(),
        ),
    ]
