# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0012_auto_20170515_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slsdatapoint',
            name='binom_fdr',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='slsdatapoint',
            name='fcpv_control_1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='slsdatapoint',
            name='fcpv_control_2',
            field=models.FloatField(),
        ),
    ]
