# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0014_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='slsdatapoint',
            name='pv_control_1',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slsdatapoint',
            name='pv_control_2',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slsdatapoint',
            name='pv_control_3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slsdatapoint',
            name='pv_control_4',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
