# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniqueref', '0015_auto_20170628_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='slsdatapoint',
            name='antisense_normalized',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slsdatapoint',
            name='sense_normalized',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
